---
# tasks file for openam

- include: install/main.yml
  static: no
  when: not uninstall

- include: config/main.yml
  static: no
  when: not uninstall

- include: uninstall/main.yml
  static: no
  when: uninstall
