---
# Enables replication between two OpenDJ instances
# Assume the "master" instance is on localhost
#

- name: Enable DJ replication
  command: '{{dsreplication}} enable
      --host1 {{ansible_fqdn}} --port1 {{opendj_admin_port}}
      --bindDN1 "cn=directory manager" --bindPassword1 {{opendj_password}}
      --replicationPort1 {{opendj_replication_port}}
      --host2 {{opendj_host2}} --port2 {{opendj_admin_port2}}
      --bindDN2 "cn=directory manager" --bindPassword2 {{opendj_password2}}
      --replicationPort2 {{opendj_replication_port2}}
      --adminUID {{opendj_replication_admin}} --adminPassword {{opendj_replication_password}}
      --baseDN "{{base_dn}}" -X -n'
  ignore_errors: yes

- name: Initialize DJ replication
  command: '{{dsreplication}} initialize-all
      --adminUID {{opendj_replication_admin}} --adminPassword {{opendj_replication_password}}
      --baseDN "{{base_dn}}"
      --hostname {{ansible_fqdn}}
      --port {{opendj_admin_port}}
      --trustAll
      --no-prompt'
  ignore_errors: yes
#- name: Check DJ replication status
#  command: '{{dsreplication}} status -h {{opendj_host}} -p {{opendj_admin_port}} --trustAll --adminUID {{opendj_replication_admin}} --adminPassword {{opendj_replication_password}}'
